export const MOCK_DATA: {
  [key: string]: {
    id: string;
    image: string;
    name: string;
    description: string;
    volume: string;
    marketCap: string;
    time: string;
    holders: number;
    proTraders: number;
    KOLs: number;
    migration: number;
    created: number;
    spinnersHolding: string;
    insidersHolding: string;
    bundleHolding: string;
  }[];
} = {
  "new-pairs": [
    {
      id: "sdf4535",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "XYZ",
      description: "Trip To Sonalia",
      volume: "$3K",
      marketCap: "$23K",
      time: "4s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 0,
      created: 5,
      spinnersHolding: "20%",
      insidersHolding: "20%",
      bundleHolding: "20%",
    },
    {
      id: "sdf4536",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "Pqeqwer",
      description: "Trip To Dubai",
      volume: "$3K",
      marketCap: "$23M",
      time: "6s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 3,
      created: 5,
      spinnersHolding: "50%",
      insidersHolding: "30%",
      bundleHolding: "20%",
    },
    {
      id: "sdf4537",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "QWE",
      description: "Trip To QWE",
      volume: "$3K",
      marketCap: "$123K",
      time: "7s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 0,
      created: 5,
      spinnersHolding: "60%",
      insidersHolding: "70%",
      bundleHolding: "10%",
    },
    {
      id: "sdf4538",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "ERT",
      description: "Trip To ERT",
      volume: "$3K",
      marketCap: "$234K",
      time: "10s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 3,
      created: 5,
      spinnersHolding: "20%",
      insidersHolding: "20%",
      bundleHolding: "20%",
    },
    {
      id: "sdf4539",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "ASD",
      description: "Trip To ASD",
      volume: "$3K",
      marketCap: "$50K",
      time: "4s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 3,
      created: 5,
      spinnersHolding: "20%",
      insidersHolding: "20%",
      bundleHolding: "20%",
    },
    {
      id: "sdf4540",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "DGD",
      description: "Trip To DGD",
      volume: "$3K",
      marketCap: "$23K",
      time: "4s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 3,
      created: 5,
      spinnersHolding: "20%",
      insidersHolding: "20%",
      bundleHolding: "20%",
    },
    {
      id: "sdf4541",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "sdsdg",
      description: "Trip To sdsdg",
      volume: "$3K",
      marketCap: "$23K",
      time: "4s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 3,
      created: 5,
      spinnersHolding: "20%",
      insidersHolding: "20%",
      bundleHolding: "20%",
    },
    {
      id: "sdf4542",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "XYZ",
      description: "Trip To Sonalia",
      volume: "$3K",
      marketCap: "$23K",
      time: "4s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 3,
      created: 5,
      spinnersHolding: "20%",
      insidersHolding: "20%",
      bundleHolding: "20%",
    },
  ],
  "final-stretch": [
    {
      id: "sdf4536",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "Pqeqwer",
      description: "Trip To Dubai",
      volume: "$3K",
      marketCap: "$23M",
      time: "6s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 3,
      created: 5,
      spinnersHolding: "50%",
      insidersHolding: "30%",
      bundleHolding: "20%",
    },
    {
      id: "sdf4535",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "XYZ",
      description: "Trip To Sonalia",
      volume: "$3K",
      marketCap: "$23K",
      time: "4s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 0,
      created: 5,
      spinnersHolding: "20%",
      insidersHolding: "20%",
      bundleHolding: "20%",
    },
    {
      id: "sdf4538",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "ERT",
      description: "Trip To ERT",
      volume: "$3K",
      marketCap: "$234K",
      time: "10s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 3,
      created: 5,
      spinnersHolding: "20%",
      insidersHolding: "20%",
      bundleHolding: "20%",
    },
    {
      id: "sdf4537",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "QWE",
      description: "Trip To QWE",
      volume: "$3K",
      marketCap: "$123K",
      time: "7s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 3,
      created: 5,
      spinnersHolding: "60%",
      insidersHolding: "70%",
      bundleHolding: "10%",
    },

    {
      id: "sdf4539",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "ASD",
      description: "Trip To ASD",
      volume: "$3K",
      marketCap: "$50K",
      time: "4s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 3,
      created: 5,
      spinnersHolding: "20%",
      insidersHolding: "20%",
      bundleHolding: "20%",
    },
    {
      id: "sdf4540",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "DGD",
      description: "Trip To DGD",
      volume: "$3K",
      marketCap: "$23K",
      time: "4s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 0,
      created: 5,
      spinnersHolding: "20%",
      insidersHolding: "20%",
      bundleHolding: "20%",
    },
    {
      id: "sdf4542",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "XYZ",
      description: "Trip To Sonalia",
      volume: "$3K",
      marketCap: "$23K",
      time: "4s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 3,
      created: 5,
      spinnersHolding: "20%",
      insidersHolding: "20%",
      bundleHolding: "20%",
    },
    {
      id: "sdf4541",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "sdsdg",
      description: "Trip To sdsdg",
      volume: "$3K",
      marketCap: "$23K",
      time: "4s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 3,
      created: 5,
      spinnersHolding: "20%",
      insidersHolding: "20%",
      bundleHolding: "20%",
    },
  ],
  migrated: [
    {
      id: "sdf4542",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "XYZ",
      description: "Trip To Sonalia",
      volume: "$3K",
      marketCap: "$23K",
      time: "4s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 3,
      created: 5,
      spinnersHolding: "20%",
      insidersHolding: "20%",
      bundleHolding: "20%",
    },
    {
      id: "sdf4538",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "ERT",
      description: "Trip To ERT",
      volume: "$3K",
      marketCap: "$234K",
      time: "10s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 0,
      created: 5,
      spinnersHolding: "20%",
      insidersHolding: "20%",
      bundleHolding: "20%",
    },
    {
      id: "sdf4535",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "XYZ",
      description: "Trip To Sonalia",
      volume: "$3K",
      marketCap: "$23K",
      time: "4s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 3,
      created: 5,
      spinnersHolding: "20%",
      insidersHolding: "20%",
      bundleHolding: "20%",
    },
    {
      id: "sdf4536",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "Pqeqwer",
      description: "Trip To Dubai",
      volume: "$3K",
      marketCap: "$23M",
      time: "6s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 3,
      created: 5,
      spinnersHolding: "50%",
      insidersHolding: "30%",
      bundleHolding: "20%",
    },
    {
      id: "sdf4537",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "QWE",
      description: "Trip To QWE",
      volume: "$3K",
      marketCap: "$123K",
      time: "7s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 0,
      created: 5,
      spinnersHolding: "60%",
      insidersHolding: "70%",
      bundleHolding: "10%",
    },

    {
      id: "sdf4539",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "ASD",
      description: "Trip To ASD",
      volume: "$3K",
      marketCap: "$50K",
      time: "4s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 3,
      created: 5,
      spinnersHolding: "20%",
      insidersHolding: "20%",
      bundleHolding: "20%",
    },
    {
      id: "sdf4540",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "DGD",
      description: "Trip To DGD",
      volume: "$3K",
      marketCap: "$23K",
      time: "4s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 3,
      created: 5,
      spinnersHolding: "20%",
      insidersHolding: "20%",
      bundleHolding: "20%",
    },
    {
      id: "sdf4541",
      image:
        "https://axiomtrading.sfo3.cdn.digitaloceanspaces.com/HwjsYXkPHzz6rFoeNpe5siMLrc1u91kKvSna6wMupump.webp",
      name: "sdsdg",
      description: "Trip To sdsdg",
      volume: "$3K",
      marketCap: "$23K",
      time: "4s",
      holders: 1,
      proTraders: 3,
      KOLs: 4,
      migration: 3,
      created: 5,
      spinnersHolding: "20%",
      insidersHolding: "20%",
      bundleHolding: "20%",
    },
  ],
};
